name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    # env:
    #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # permissions:
    #   contents: write
    steps:
      # - name: Register npm token
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # NOTE: Hard Coded Node Version
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install semver
        run: |
          yarn add semver-compare-cli
          yarn semver-compare -v

          RESULT1=$(./node_modules/.bin/semver-compare 1.0.0 gt 2.0.0) || EXIT_CODE=$?
          echo "RESULT1:" $RESULT1
          if [ "$EXIT_CODE" = "0" ]; then
            echo "version_updated=true" >> $GITHUB_OUTPUT
          else
            echo "version_updated=false" >> $GITHUB_OUTPUT
          fi

          RESULT2=$(./node_modules/.bin/semver-compare 2.0.0 gt 2.0.0) || EXIT_CODE2=$?
          if [ "$EXIT_CODE2" = "0" ]; then
            echo "version_updated=true" >> $GITHUB_OUTPUT
          else
            echo "version_updated=false" >> $GITHUB_OUTPUT
          fi

          RESULT2=$(./node_modules/.bin/semver-compare 3.0.0 gt 2.0.0) || EXIT_CODE3=$?
          if [ "$EXIT_CODE3" = "0" ]; then
            echo "version_updated=true" >> $GITHUB_OUTPUT
          else
            echo "version_updated=false" >> $GITHUB_OUTPUT
          fi